name: Deploy app

on:
  push:
    branches:
      - main
      - cd

jobs:
  build_image_and_push:
    name: Build and push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get app version
        id: app-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            snapfork/snapforkfrontend:latest
            snapfork/snapforkfrontend:${{steps.app-version.outputs.current-version}}
      - name: Show new version
        run: echo 'New version snapfork-frontend:${{steps.app-version.outputs.current-version}} generated'
        shell: bash
  deploy_new_image:
    needs: [build_image_and_push]
    name: Deploy the new image for frontend in the server
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH Command
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /app/snapfork/
            ./deploy.sh frontend
