name: Tests

on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v1
    with:
      node-version: '12'
      check-latest: true
  - run: npm install
  - run: npm test
